// Generated by CoffeeScript 1.4.0
(function() {
  var Database, fs, inspect, isFunction, makeId, os, path, pick, sha1, shuffle, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  inspect = require("util").inspect;

  path = require("path");

  os = require("os");

  fs = require("fs");

  _ref = require('../common'), isFunction = _ref.isFunction, makeId = _ref.makeId, sha1 = _ref.sha1, shuffle = _ref.shuffle, pick = _ref.pick;

  Database = (function() {

    function Database(max_size) {
      this.max_size = max_size != null ? max_size : 100;
      this.next = __bind(this.next, this);

      this.decimate = __bind(this.decimate, this);

      this.oldestGeneration = __bind(this.oldestGeneration, this);

      this.size = __bind(this.size, this);

      this.record = __bind(this.record, this);

      this.remove = __bind(this.remove, this);

      this.pick = __bind(this.pick, this);

      this.load = __bind(this.load, this);

      this._ = {};
      this.length = 0;
      this.counter = 0;
      this.batch = [];
    }

    Database.prototype.load = function(input) {
      var g, generation, hash, i, id, split, src;
      console.log("importing " + input);
      src = "";
      id = makeId();
      generation = 0;
      if (isFunction(input)) {
        src = file.toString();
      } else {
        src = fs.readFileSync(input, "utf8");
        split = input.split('-');
        g = split[0];
        if (g != null) {
          generation = Number(g);
        }
        i = split[1];
        if (i != null) {
          id = Number(i);
        }
      }
      hash = sha1(src);
      return this.record({
        src: src,
        id: id,
        generation: generation,
        hash: hash,
        stats: {}
      });
    };

    Database.prototype.pick = function() {
      return this._[deck.pick(Object.keys(this._))];
    };

    Database.prototype.remove = function(g) {
      return delete this._[g.id];
    };

    Database.prototype.record = function(g) {
      this._[g.id] = g;
      return this.counter++;
    };

    Database.prototype.size = function() {
      return Object.keys(this._).length;
    };

    Database.prototype.oldestGeneration = function() {
      var k, oldest, v, _ref1;
      oldest = 0;
      _ref1 = this._;
      for (k in _ref1) {
        v = _ref1[k];
        if (v.generation > oldest) {
          oldest = v.generation;
        }
      }
      return oldest;
    };

    Database.prototype.decimate = function() {
      var k, keys, size, to_remove, _i, _len, _ref1, _results;
      size = this.size();
      if (size < this.max_size) {
        return;
      }
      to_remove = size - this.max_size;
      keys = deck.shuffle(Object.keys(this._));
      _ref1 = keys.slice(0, to_remove);
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        k = _ref1[_i];
        _results.push(delete this._[k]);
      }
      return _results;
    };

    Database.prototype.next = function() {
      var k;
      k = this.batch.pop();
      if (!(k != null) && this.size() > 0) {
        this.decimate();
        this.batch = deck.shuffle(Object.keys(this._));
        k = this.batch.pop();
      }
      return this._[k];
    };

    return Database;

  })();

  module.exports = Database;

}).call(this);
