// Generated by CoffeeScript 1.4.0
(function() {
  var defaultLogger,
    _this = this;

  defaultLogger = function(value, msg) {
    if (msg == null) {
      msg = '';
    }
    return console.log("" + value + " points error: " + msg);
  };

  module.exports = function(onUpdate) {
    if (onUpdate == null) {
      onUpdate = defaultLogger;
    }
    return {
      trivial: function(msg) {
        if (msg == null) {
          msg = '';
        }
        return onUpdate(10, msg);
      },
      minor: function(msg) {
        if (msg == null) {
          msg = '';
        }
        return onUpdate(50, msg);
      },
      medium: function(msg) {
        if (msg == null) {
          msg = '';
        }
        return onUpdate(500, msg);
      },
      major: function(msg) {
        if (msg == null) {
          msg = '';
        }
        return onUpdate(5000, msg);
      },
      critical: function(msg) {
        if (msg == null) {
          msg = '';
        }
        return onUpdate(10000, msg);
      },
      fatal: function(msg) {
        if (msg == null) {
          msg = '';
        }
        throw new Error("fatal error: " + msg);
      }
    };
  };

}).call(this);
