// Generated by CoffeeScript 1.4.0
(function() {
  var Database, Master, NB_CORES, P, Stats, Stream, cluster, debug, inspect, isFunction, makeId, pretty, repeat, timmy, wait, _ref, _ref1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  inspect = require('util').inspect;

  cluster = require('cluster');

  Stream = require('stream');

  _ref = require('ragtime'), repeat = _ref.repeat, wait = _ref.wait;

  timmy = require('timmy');

  Database = require('./database');

  Stats = require('./stats');

  _ref1 = require('./common'), P = _ref1.P, isFunction = _ref1.isFunction, makeId = _ref1.makeId, NB_CORES = _ref1.NB_CORES, pretty = _ref1.pretty;

  debug = function(msg) {
    if (true) {
      return console.log("" + msg);
    }
  };

  Master = (function(_super) {

    __extends(Master, _super);

    function Master(options) {
      var agent, agentConfigurator, bootstrap, database, databaseSize, debugInterval, emit, i, log, logLevel, maxGenerations, nbGenerations, restart_delay, spawn, stopIfEmpty, workersByMachine, _i, _len, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9,
        _this = this;
      if (options == null) {
        options = {};
      }
      this.each = __bind(this.each, this);

      this.min = __bind(this.min, this);

      this.max = __bind(this.max, this);

      this.reduce = __bind(this.reduce, this);

      this.agents = __bind(this.agents, this);

      this.remove = __bind(this.remove, this);

      this.add = __bind(this.add, this);

      this.size = __bind(this.size, this);

      this.onDie = __bind(this.onDie, this);

      this.onFork = __bind(this.onFork, this);

      this.onMsg = __bind(this.onMsg, this);

      workersByMachine = this.workersByMachine = (_ref2 = options.workersByMachine) != null ? _ref2 : NB_CORES;
      databaseSize = this.databaseSize = (_ref3 = options.databaseSize) != null ? _ref3 : 10;
      debugInterval = this.debugInterval = (_ref4 = options.debugInterval) != null ? _ref4 : 2..sec;
      maxGenerations = this.maxGenerations = (_ref5 = options.maxGenerations) != null ? _ref5 : Infinity;
      logLevel = this.logLevel = (_ref6 = options.logLevel) != null ? _ref6 : 0;
      stopIfEmpty = this.stopIfEmpty = (_ref7 = options.stopIfEmpty) != null ? _ref7 : true;
      agentConfigurator = (_ref8 = options.config) != null ? _ref8 : function() {
        return {};
      };
      restart_delay = 500..ms;
      nbGenerations = 0;
      this.isMaster = true;
      database = this.database = new Database(databaseSize);
      bootstrap = (_ref9 = options.bootstrap) != null ? _ref9 : [];
      emit = function(key, msg) {
        return _this.emit(key, msg);
      };
      log = function(msg) {
        return console.log("MASTER: " + msg);
      };
      log("loading " + bootstrap.length + " agents");
      for (_i = 0, _len = bootstrap.length; _i < _len; _i++) {
        agent = bootstrap[_i];
        database.add(agent);
      }
      spawn = function() {
        var send, worker, _j, _len1, _ref10;
        if (++nbGenerations > maxGenerations) {
          log("max generations reached, stopping system");
          _ref10 = cluster.workers;
          for (_j = 0, _len1 = _ref10.length; _j < _len1; _j++) {
            worker = _ref10[_j];
            worker.destroy();
          }
          process.exit(0);
        }
        worker = cluster.fork();
        send = function(msg) {
          return worker.send(JSON.stringify(msg));
        };
        return worker.on('message', function(msg) {
          var _base, _k, _len2, _ref11, _ref12;
          msg = JSON.parse(msg);
          emit('message', msg);
          if ('ready' in msg) {
            agent = database.next();
            if (agent != null) {
              worker.agent = agent;
              agent.name = ("" + agent.id).slice(-8);
              agent.config = agentConfigurator(agent);
              if ((_ref11 = (_base = agent.config).logLevel) == null) {
                _base.logLevel = logLevel != null ? logLevel : 0;
              }
              send(agent);
            } else {
              if (stopIfEmpty) {
                log("no more agent to send, stopping system");
                _ref12 = cluster.workers;
                for (_k = 0, _len2 = _ref12.length; _k < _len2; _k++) {
                  worker = _ref12[_k];
                  worker.destroy();
                }
                process.exit(0);
              } else {
                log("waiting..");
              }
            }
          }
          if ('fork' in msg) {
            process.nextTick(function() {
              return _this.onFork(msg.fork, function(ok) {
                if (ok != null) {
                  database.record(ok);
                } else {
                  return;
                }
              });
            });
          }
          if ('die' in msg) {
            process.nextTick(function() {
              return _this.onDie(agent, function(granted) {
                if (granted) {
                  database.remove(agent.id);
                } else {
                  return;
                }
              });
            });
          }
          if ('msg' in msg) {
            return process.nextTick(function() {
              return _this.onMsg(agent, msg.msg);
            });
          }
        });
      };
      cluster.on("exit", function(worker, code, signal) {
        log(("worker " + worker.id + " exited: ") + (code > 0 ? ("" + code).red : ("" + code).green));
        return wait(restart_delay)(function() {
          return spawn();
        });
      });
      i = 0;
      while (i++ < workersByMachine) {
        spawn();
      }
      this.emit('ready');
    }

    Master.prototype.onMsg = function(agent, msg) {};

    Master.prototype.onFork = function(agent, onComplete) {
      onComplete(true);
      return true;
    };

    Master.prototype.onDie = function(agent, onComplete) {
      return onComplete(true);
    };

    Master.prototype.size = function() {
      return this.database.length;
    };

    Master.prototype.add = function(agent) {
      return this.database.add(agent);
    };

    Master.prototype.remove = function(agent) {
      return this.database.remove(agent);
    };

    Master.prototype.agents = function(property) {
      return this.database.agents(property);
    };

    Master.prototype.reduce = function(f) {
      return this.database.reduce(f);
    };

    Master.prototype.max = function(f) {
      return this.database.max(f);
    };

    Master.prototype.min = function(f) {
      return this.database.min(f);
    };

    Master.prototype.each = function(f) {
      return this.database.each(f);
    };

    return Master;

  })(Stream);

  module.exports = function(args) {
    return new Master(args);
  };

}).call(this);
