// Generated by CoffeeScript 1.6.3
(function() {
  var Master, Worker, cluster;

  cluster = require('cluster');

  Master = require('./master');

  Worker = require('./worker');

  exports.common = require('./common');

  exports.Petri = function(opts) {
    if (opts == null) {
      opts = {};
    }
    if (cluster.isMaster) {
      return Master(opts);
    } else {
      return Worker();
    }
  };

  exports.isMaster = cluster.isMaster;

}).call(this);
