// Generated by CoffeeScript 1.6.3
(function() {
  var Master, Worker, cluster, common, errors, inspect;

  inspect = require('util').inspect;

  cluster = require('cluster');

  Master = require('./master');

  Worker = require('./worker');

  common = require('./common');

  errors = require('./errors');

  exports.NB_CORES = common.NB_CORES;

  exports.common = common;

  exports.errors = errors;

  exports.Petri = function(options) {
    if (options == null) {
      options = {};
    }
    if (cluster.isMaster) {
      return Master(options);
    } else {
      return Worker();
    }
  };

  exports.isMaster = cluster.isMaster;

}).call(this);
