// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(foo) {
    if (foo == null) {
      foo = 'bar';
    }
    return {
      job: 0,
      map: function(N) {
        return {
          foo: 'bar'
        };
      },
      reduce: function(job, _arg) {
        var foo;
        foo = _arg.foo;
      },
      stats: function() {
        return {
          job_status: "0"
        };
      }
    };
  };

}).call(this);
