// Generated by CoffeeScript 1.4.0
(function() {
  var P, Stats, common, inspect, isFunction, puts, wait,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  inspect = require('util').inspect;

  puts = require('sys').puts;

  Stats = require('./stats');

  common = require('./common');

  wait = require("ragtime").wait;

  P = common.P, isFunction = common.isFunction;

  module.exports = (function() {

    function exports(options) {
      var data, k, v, worker, _ref, _ref1, _ref2, _workers;
      if (options == null) {
        options = {};
      }
      this.decimate = __bind(this.decimate, this);

      this.start = __bind(this.start, this);

      this.input = (_ref = options.input) != null ? _ref : function() {};
      this.output = (_ref1 = options.output) != null ? _ref1 : function() {};
      this.frequency = (_ref2 = options.frequency) != null ? _ref2 : 1000;
      this.workers = [];
      if (options.workers != null) {
        _workers = options.workers;
        if (isFunction(_workers)) {
          _workers = _workers();
        }
        this.workers = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = _workers.length; _i < _len; _i++) {
            worker = _workers[_i];
            data = {
              kernel: function() {}
            };
            for (k in worker) {
              v = worker[k];
              if (k === 'kernel') {
                data.kernel = isFunction(v) ? v : eval(v);
              } else {
                data[k] = v;
              }
            }
            _results.push(data);
          }
          return _results;
        })();
      }
      this.stats = new Stats(this, ['balance']);
    }

    exports.prototype.start = function() {
      var frequency, inputFunc, iterations, outputFunc, sync, _,
        _this = this;
      frequency = this.frequency;
      inputFunc = this.input;
      outputFunc = this.output;
      sync = function(f) {
        return wait(_this.frequency)(function() {
          _this.stats.update();
          return f();
        });
      };
      iterations = 0;
      return (_ = function() {
        return sync(function() {
          var inputs, outputs, worker;
          iterations += 1;
          puts("iteration #" + iterations + ": " + _this.workers.length + " workers remaining");
          _this.workers = (function() {
            var _i, _len, _ref, _results;
            _ref = this.workers;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              worker = _ref[_i];
              puts("preparing input data");
              inputs = inputFunc({}, worker);
              puts("running kernel + outputs");
              outputs = {};
              try {
                outputs = worker.kernel(inputs);
              } catch (e1) {
                puts("killing individual (bad kernel: " + e1 + ")");
                continue;
              }
              try {
                outputFunc(this.stats, {}, worker, outputs);
              } catch (e2) {
                puts("killing individual (bad output: " + e2 + ")");
                continue;
              }
              _results.push(worker);
            }
            return _results;
          }).call(_this);
          return _();
        });
      })();
    };

    exports.prototype.decimate = function() {
      return console.log("stats: " + (inspect(this.stats)));
    };

    return exports;

  })();

}).call(this);
