// Generated by CoffeeScript 1.4.0
(function() {
  var P, Stats, common, debug, inspect, isFunction, pretty, wait,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  inspect = require('util').inspect;

  wait = require('ragtime').wait;

  Stats = require('./stats');

  common = require('./common');

  P = common.P, isFunction = common.isFunction;

  debug = function(msg) {
    if (true) {
      return console.log("" + msg);
    }
  };

  pretty = function(obj) {
    return "" + (inspect(obj, false, 20, true));
  };

  module.exports = (function() {

    function exports(options) {
      var data, k, stats, v, worker, _ref, _ref1, _workers;
      if (options == null) {
        options = {};
      }
      this.decimate = __bind(this.decimate, this);

      this.start = __bind(this.start, this);

      this.connector = options.connector;
      this.frequency = (_ref = options.frequency) != null ? _ref : 1000;
      stats = (_ref1 = options.stats) != null ? _ref1 : {
        energy: function(worker) {
          return worker.energy;
        }
      };
      this.workers = [];
      if (options.workers != null) {
        _workers = options.workers;
        if (isFunction(_workers)) {
          _workers = _workers();
        }
        this.workers = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = _workers.length; _i < _len; _i++) {
            worker = _workers[_i];
            data = {
              kernel: function() {}
            };
            for (k in worker) {
              v = worker[k];
              if (k === 'kernel') {
                data.kernel = isFunction(v) ? v : eval(v);
              } else {
                data[k] = v;
              }
            }
            _results.push(data);
          }
          return _results;
        })();
      }
      this.stats = new Stats(this, stats);
    }

    exports.prototype.start = function() {
      var connector, frequency, iterations, sync, _,
        _this = this;
      frequency = this.frequency;
      connector = this.connector;
      sync = function(f) {
        return wait(_this.frequency)(function() {
          _this.stats.update();
          return f();
        });
      };
      iterations = 0;
      return (_ = function() {
        return sync(function() {
          var inputs, outputs, worker;
          iterations += 1;
          debug("iteration #" + iterations + ": " + _this.workers.length + " workers remaining");
          _this.workers = (function() {
            var _i, _len, _ref, _results;
            _ref = this.workers;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              worker = _ref[_i];
              debug("preparing input data");
              inputs = connector.input({}, worker);
              debug("running kernel on inputs: " + pretty(inputs));
              outputs = {};
              try {
                outputs = worker.kernel(inputs);
              } catch (e1) {
                debug("killing individual (bad kernel: " + e1 + ")");
                continue;
              }
              try {
                connector.output(this.stats, {}, worker, outputs);
              } catch (e2) {
                debug("killing individual (bad output: " + e2 + ")");
                continue;
              }
              _results.push(worker);
            }
            return _results;
          }).call(_this);
          return _();
        });
      })();
    };

    exports.prototype.decimate = function() {
      return debug("stats: " + (inspect(this.stats)));
    };

    return exports;

  })();

}).call(this);
