// Generated by CoffeeScript 1.4.0
(function() {
  var Master, Stats, System, Worker, cluster, common, errors, inspect;

  inspect = require('util').inspect;

  cluster = require('cluster');

  Master = require('./master');

  Worker = require('./worker');

  common = require('./common');

  errors = require('./errors');

  Stats = require('./stats');

  exports.NB_CORES = common.NB_CORES;

  exports.common = common;

  exports.Stats = Stats;

  exports.errors = errors;

  System = (function() {

    function System(options) {
      if (options == null) {
        options = {};
      }
      (cluster.isMaster ? Master : Worker)(options);
    }

    return System;

  })();

  exports.System = System;

}).call(this);
