// Generated by CoffeeScript 1.4.0
(function() {
  var common, exec, master, start, worker;

  master = require('./master/master');

  worker = require('./worker/worker');

  common = require('./common');

  exports.NB_CORES = common.NB_CORES;

  exports.master = master;

  exports.worker = worker;

  exports.start = start = function(options) {
    var cluster, conf, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;
    if (options == null) {
      options = {};
    }
    console.log("START");
    cluster = require('cluster');
    require('timmy');
    if (cluster.isMaster) {
      console.log("IS MASTER");
      conf = (_ref = options.master) != null ? _ref : {};
      return master({
        db_size: (_ref1 = conf.db_size) != null ? _ref1 : 100,
        nb_cores: (_ref2 = conf.nb_cores) != null ? _ref2 : common.NB_CORES,
        sampling_delay: (_ref3 = conf.sampling_delay) != null ? _ref3 : 2..sec
      });
    } else {
      console.log("IS WORKER");
      conf = (_ref4 = options.worker) != null ? _ref4 : {};
      return worker({
        size: (_ref5 = conf.size) != null ? _ref5 : 10,
        max_iterations: (_ref6 = conf.max_iterations) != null ? _ref6 : 2,
        update_frequency: (_ref7 = conf.update_frequency) != null ? _ref7 : 1..sec
      });
    }
  };

  exec = process.argv[1];

  if ('substrate' === exec.slice(-9) || 'substrate.js' === exec.slice(-11)) {
    start();
  }

}).call(this);
