// Generated by CoffeeScript 1.4.0
(function() {
  var Master, Worker, cluster, inspect;

  inspect = require('util').inspect;

  cluster = require('cluster');

  Master = require('./master');

  Worker = require('./worker');

  module.exports = (function() {

    function exports(options) {
      if (options == null) {
        options = {};
      }
      if (cluster.isMaster) {
        console.log("IS MASTER");
        master(options);
      } else {
        console.log("IS WORKER");
        worker(options);
      }
    }

    return exports;

  })();

}).call(this);
