// Generated by CoffeeScript 1.4.0
(function() {
  var calloc,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  calloc = function(N, f) {
    var i, _i, _results;
    if (f == null) {
      f = function() {
        return 0;
      };
    }
    _results = [];
    for (i = _i = 0; 0 <= N ? _i < N : _i > N; i = 0 <= N ? ++_i : --_i) {
      _results.push({
        inputs: [],
        value: f()
      });
    }
    return _results;
  };

  module.exports = (function() {

    function exports(max_size) {
      this.max_size = max_size;
      this.randindex = __bind(this.randindex, this);

      this.get = __bind(this.get, this);

      this.pick = __bind(this.pick, this);

      this._ = calloc(this.max_size, function() {
        return Math.random();
      });
    }

    exports.prototype.pick = function() {
      return pick(this._);
    };

    exports.prototype.get = function(i) {
      return this._[i];
    };

    exports.prototype.randindex = function() {
      return Math.round(Math.random() * (this.memory.length - 1));
    };

    return exports;

  })();

}).call(this);
